// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonDrive.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutonDrive::AutonDrive(): Command() {
	float currentDistance = 0;

        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutonDrive::Initialize() {
	RobotMap::driveTraindriveEncoder->Reset();

}

// Called repeatedly when this Command is scheduled to run
void AutonDrive::Execute(float goalDistance) {
	currentDistance = RobotMap::driveTraindriveEncoder->Get();
	float power = -1 / goalDistance * currentDistance + 1;
	RobotMap::driveTrainRobotDrive41->TankDrive(power,power);
}

// Make this return true when this Command no longer needs to run execute()
bool AutonDrive::IsFinished() {
    return (currentDistance == goalDistance);
}

// Called once after isFinished returns true
void AutonDrive::End() {
	RobotMap::driveTraindriveEncoder->Reset();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonDrive::Interrupted() {

}
