// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveTrainDriveTalon1 = NULL;
SpeedController* RobotMap::driveTrainDriveTalon3 = NULL;
SpeedController* RobotMap::driveTrainDriveTalon2 = NULL;
SpeedController* RobotMap::driveTrainDriveTalon4 = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveTrainDriveTalon1 = new Talon(0);
	lw->AddActuator("DriveTrain", "DriveTalon1", (Talon*) driveTrainDriveTalon1);
	
	driveTrainDriveTalon3 = new Talon(2);
	lw->AddActuator("DriveTrain", "DriveTalon3", (Talon*) driveTrainDriveTalon3);
	
	driveTrainDriveTalon2 = new Talon(1);
	lw->AddActuator("DriveTrain", "DriveTalon2", (Talon*) driveTrainDriveTalon2);
	
	driveTrainDriveTalon4 = new Talon(3);
	lw->AddActuator("DriveTrain", "DriveTalon4", (Talon*) driveTrainDriveTalon4);
	

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
